import Itinerary from '../models/Itinerary.js';
import Trip from '../models/Trip.js';
import { generateItinerary, generateAlternativeItinerary, validateItinerary } from '../services/aiService.js';

// @desc    Generate AI itinerary for a trip
// @route   POST /api/itineraries/generate
// @access  Private (requires JWT)
const generateItineraryForTrip = async (req, res) => {
  try {
    const startTime = Date.now();
    const { tripId, preferences } = req.body;

    // Validate required fields
    if (!tripId) {
      return res.status(400).json({ 
        message: 'Trip ID is required' 
      });
    }

    // Get the trip and verify ownership
    const trip = await Trip.findOne({
      _id: tripId,
      userId: req.user._id
    });

    if (!trip) {
      return res.status(404).json({ 
        message: 'Trip not found or access denied' 
      });
    }

    // Check if trip has required dates
    if (!trip.startDate || !trip.endDate) {
      return res.status(400).json({ 
        message: 'Trip must have start and end dates to generate itinerary' 
      });
    }

    // Prepare inputs for AI service - Only basic trip info, no external API data
    const inputs = {
      destination: trip.destination,
      startDate: trip.startDate,
      endDate: trip.endDate,
      interests: preferences?.interests || ['exploration', 'culture', 'food'],
      budget: preferences?.budget || 'flexible',
      groupSize: preferences?.groupSize || 1,
      timeLimits: preferences?.timeLimits || null,
      weather: preferences?.weather || null,
      accessibility: preferences?.accessibility || null,
      forceRefresh: preferences?.forceRefresh === true
    };

    // Generate itinerary using AI - No external API data needed
    const generatedItinerary = await generateItinerary(inputs);

    // Validate the generated itinerary
    const validation = validateItinerary(generatedItinerary);
    if (!validation.valid) {
      return res.status(500).json({ 
        message: 'Generated itinerary is invalid',
        error: validation.error 
      });
    }

    // Calculate generation time
    const generationTime = Date.now() - startTime;

    // Create itinerary document
    const itinerary = new Itinerary({
      tripId: tripId,
      userId: req.user._id,
      plan: generatedItinerary,
      constraintsUsed: {
        budget: inputs.budget,
        timeLimits: inputs.timeLimits,
        weather: inputs.weather,
        accessibility: inputs.accessibility,
        groupSize: inputs.groupSize,
        interests: inputs.interests
      },
      generationMetadata: {
        aiProvider: 'gemini',
        modelUsed: 'gemini-1.5-flash',
        generationTime: generationTime,
        tokensUsed: 0, // Could be updated if API provides this info
        cacheHit: false,
        note: 'Itinerary structure generated by AI, external APIs handle transport/hotels/restaurants'
      }
    });

    // Save the itinerary
    await itinerary.save();

    res.status(201).json({
      success: true,
      message: 'Itinerary structure generated successfully',
      data: {
        itinerary: itinerary,
        generationTime: `${generationTime}ms`,
        trip: {
          id: trip._id,
          title: trip.title,
          destination: trip.destination,
          startDate: trip.startDate,
          endDate: trip.endDate
        },
        note: 'Transport, hotel, and restaurant options are available via separate API endpoints'
      }
    });
  } catch (error) {
    console.error('Generate itinerary error:', error);
    res.status(500).json({ 
      message: 'Failed to generate itinerary',
      error: error.message 
    });
  }
};

// @desc    Get all itineraries for a user
// @route   GET /api/itineraries
// @access  Private (requires JWT)
const getUserItineraries = async (req, res) => {
  try {
    const { tripId, status, limit = 10, page = 1 } = req.query;

    // Build query
    const query = { userId: req.user._id };
    if (tripId) query.tripId = tripId;
    if (status) query.status = status;

    // Execute query with pagination
    const itineraries = await Itinerary.find(query)
      .populate('tripId', 'title destination startDate endDate')
      .sort({ generatedAt: -1 })
      .limit(parseInt(limit))
      .skip((parseInt(page) - 1) * parseInt(limit));

    // Get total count for pagination
    const total = await Itinerary.countDocuments(query);

    res.json({
      success: true,
      data: itineraries,
      pagination: {
        currentPage: parseInt(page),
        totalPages: Math.ceil(total / parseInt(limit)),
        totalItems: total,
        itemsPerPage: parseInt(limit)
      }
    });
  } catch (error) {
    console.error('Get user itineraries error:', error);
    res.status(500).json({ 
      message: 'Failed to fetch itineraries',
      error: error.message 
    });
  }
};

// @desc    Get specific itinerary by ID
// @route   GET /api/itineraries/:id
// @access  Private (requires JWT)
const getItineraryById = async (req, res) => {
  try {
    const { id } = req.params;

    const itinerary = await Itinerary.findOne({
      _id: id,
      userId: req.user._id
    }).populate('tripId', 'title destination startDate endDate');

    if (!itinerary) {
      return res.status(404).json({ 
        message: 'Itinerary not found or access denied' 
      });
    }

    res.json({
      success: true,
      data: itinerary
    });
  } catch (error) {
    console.error('Get itinerary by ID error:', error);
    res.status(500).json({ 
      message: 'Failed to fetch itinerary',
      error: error.message 
    });
  }
};

// @desc    Get itinerary by Trip ID (latest for the trip)
// @route   GET /api/trips/:id/itinerary
// @access  Private (requires JWT)
const getItineraryByTripId = async (req, res) => {
  try {
    const { id } = req.params;

    const itinerary = await Itinerary.findOne({
      tripId: id,
      userId: req.user._id
    })
      .sort({ generatedAt: -1 })
      .populate('tripId', 'title destination startDate endDate');

    if (!itinerary) {
      return res.status(404).json({
        message: 'Itinerary not found for this trip or access denied'
      });
    }

    res.json({
      success: true,
      data: itinerary
    });
  } catch (error) {
    console.error('Get itinerary by Trip ID error:', error);
    res.status(500).json({
      message: 'Failed to fetch itinerary for trip',
      error: error.message
    });
  }
};

// @desc    Generate alternative itinerary based on constraints
// @route   POST /api/itineraries/:id/alternatives
// @access  Private (requires JWT)
const generateAlternativeItineraryForTrip = async (req, res) => {
  try {
    const { id } = req.params;
    const { constraints } = req.body;

    if (!constraints) {
      return res.status(400).json({ 
        message: 'Constraints are required to generate alternative itinerary' 
      });
    }

    // Get the original itinerary
    const originalItinerary = await Itinerary.findOne({
      _id: id,
      userId: req.user._id
    });

    if (!originalItinerary) {
      return res.status(404).json({ 
        message: 'Itinerary not found or access denied' 
      });
    }

    // Generate alternative itinerary
    const alternativePlan = await generateAlternativeItinerary(
      originalItinerary.plan, 
      constraints
    );

    // Validate the alternative itinerary
    const validation = validateItinerary(alternativePlan);
    if (!validation.valid) {
      return res.status(500).json({ 
        message: 'Generated alternative itinerary is invalid',
        error: validation.error 
      });
    }

    // Create new itinerary document with alternative plan
    const alternativeItinerary = new Itinerary({
      tripId: originalItinerary.tripId,
      userId: req.user._id,
      plan: alternativePlan,
      constraintsUsed: {
        ...originalItinerary.constraintsUsed,
        ...constraints
      },
      generationMetadata: {
        aiProvider: 'gemini',
        modelUsed: 'gemini-1.5-flash',
        generationTime: 0,
        tokensUsed: 0,
        cacheHit: false
      },
      status: 'draft'
    });

    // Save the alternative itinerary
    await alternativeItinerary.save();

    res.status(201).json({
      success: true,
      message: 'Alternative itinerary generated successfully',
      data: {
        originalItineraryId: originalItinerary._id,
        alternativeItinerary: alternativeItinerary
      }
    });
  } catch (error) {
    console.error('Generate alternative itinerary error:', error);
    res.status(500).json({ 
      message: 'Failed to generate alternative itinerary',
      error: error.message 
    });
  }
};

// @desc    Update itinerary status
// @route   PATCH /api/itineraries/:id/status
// @access  Private (requires JWT)
const updateItineraryStatus = async (req, res) => {
  try {
    const { id } = req.params;
    const { status } = req.body;

    if (!status || !['draft', 'finalized', 'archived'].includes(status)) {
      return res.status(400).json({ 
        message: 'Valid status is required (draft, finalized, archived)' 
      });
    }

    const itinerary = await Itinerary.findOneAndUpdate(
      {
        _id: id,
        userId: req.user._id
      },
      { status },
      { new: true }
    );

    if (!itinerary) {
      return res.status(404).json({ 
        message: 'Itinerary not found or access denied' 
      });
    }

    res.json({
      success: true,
      message: 'Itinerary status updated successfully',
      data: itinerary
    });
  } catch (error) {
    console.error('Update itinerary status error:', error);
    res.status(500).json({ 
      message: 'Failed to update itinerary status',
      error: error.message 
    });
  }
};

// @desc    Rate and provide feedback for itinerary
// @route   POST /api/itineraries/:id/feedback
// @access  Private (requires JWT)
const provideItineraryFeedback = async (req, res) => {
  try {
    const { id } = req.params;
    const { rating, feedback } = req.body;

    if (!rating || rating < 1 || rating > 5) {
      return res.status(400).json({ 
        message: 'Valid rating (1-5) is required' 
      });
    }

    const itinerary = await Itinerary.findOneAndUpdate(
      {
        _id: id,
        userId: req.user._id
      },
      { 
        userRating: rating,
        userFeedback: feedback || ''
      },
      { new: true }
    );

    if (!itinerary) {
      return res.status(404).json({ 
        message: 'Itinerary not found or access denied' 
      });
    }

    res.json({
      success: true,
      message: 'Feedback submitted successfully',
      data: itinerary
    });
  } catch (error) {
    console.error('Provide itinerary feedback error:', error);
    res.status(500).json({ 
      message: 'Failed to submit feedback',
      error: error.message 
    });
  }
};

// @desc    Customize specific time slot in itinerary
// @route   PATCH /api/itineraries/:id/customize
// @access  Private (requires JWT)
const customizeItinerary = async (req, res) => {
  try {
    const { id } = req.params;
    const { day, timeSlot, customActivity, customLocation, customDuration, customCost, customNotes } = req.body;

    // Validate required fields
    if (!day || !timeSlot || !customActivity) {
      return res.status(400).json({ 
        message: 'Day, timeSlot, and customActivity are required' 
      });
    }

    // Validate timeSlot
    if (!['morning', 'afternoon', 'evening'].includes(timeSlot)) {
      return res.status(400).json({ 
        message: 'timeSlot must be morning, afternoon, or evening' 
      });
    }

    // Get the itinerary
    const itinerary = await Itinerary.findOne({
      _id: id,
      userId: req.user._id
    });

    if (!itinerary) {
      return res.status(404).json({ 
        message: 'Itinerary not found or access denied' 
      });
    }

    // Find the specific day
    const dayPlan = itinerary.plan.dailyPlans.find(d => d.day === parseInt(day));
    if (!dayPlan) {
      return res.status(404).json({ 
        message: `Day ${day} not found in itinerary` 
      });
    }

    // Store original activity in customizations
    const originalActivity = dayPlan[timeSlot];
    itinerary.customizations.modifiedActivities.push({
      day: parseInt(day),
      timeSlot: timeSlot,
      originalActivity: originalActivity.activity,
      newActivity: customActivity,
      modifiedAt: new Date()
    });

    // Update the activity with custom details
    dayPlan[timeSlot] = {
      activity: customActivity,
      location: customLocation || originalActivity.location,
      duration: customDuration || originalActivity.duration,
      cost: customCost || originalActivity.cost,
      notes: customNotes || originalActivity.notes
    };

    // Recalculate total day cost if cost was modified
    if (customCost) {
      const morningCost = parseFloat(dayPlan.morning.cost.replace('$', '')) || 0;
      const afternoonCost = parseFloat(dayPlan.afternoon.cost.replace('$', '')) || 0;
      const eveningCost = parseFloat(dayPlan.evening.cost.replace('$', '')) || 0;
      const totalDayCost = morningCost + afternoonCost + eveningCost;
      dayPlan.totalDayCost = `$${totalDayCost}`;
    }

    // Save the itinerary
    await itinerary.save();

    res.json({
      success: true,
      message: 'Itinerary customized successfully',
      data: {
        itinerary: itinerary,
        modification: {
          day: parseInt(day),
          timeSlot: timeSlot,
          originalActivity: originalActivity.activity,
          newActivity: customActivity,
          modifiedAt: new Date()
        }
      }
    });
  } catch (error) {
    console.error('Customize itinerary error:', error);
    res.status(500).json({ 
      message: 'Failed to customize itinerary',
      error: error.message 
    });
  }
};

// @desc    Get itinerary with custom modifications applied
// @route   GET /api/itineraries/:id/customized
// @access  Private (requires JWT)
const getCustomizedItinerary = async (req, res) => {
  try {
    const { id } = req.params;

    const itinerary = await Itinerary.findOne({
      _id: id,
      userId: req.user._id
    }).populate('tripId', 'title destination startDate endDate');

    if (!itinerary) {
      return res.status(404).json({ 
        message: 'Itinerary not found or access denied' 
      });
    }

    // Create a response that shows both original and customized versions
    const response = {
      success: true,
      data: {
        itinerary: itinerary,
        customizations: {
          totalModifications: itinerary.customizations.modifiedActivities.length,
          modifications: itinerary.customizations.modifiedActivities,
          addedNotes: itinerary.customizations.addedNotes,
          budgetAdjustments: itinerary.customizations.budgetAdjustments
        },
        note: 'This itinerary includes your custom modifications. Original activities are preserved in the customizations history.'
      }
    };

    res.json(response);
  } catch (error) {
    console.error('Get customized itinerary error:', error);
    res.status(500).json({ 
      message: 'Failed to fetch customized itinerary',
      error: error.message 
    });
  }
};

// @desc    Add custom note to itinerary day
// @route   POST /api/itineraries/:id/notes
// @access  Private (requires JWT)
const addCustomNote = async (req, res) => {
  try {
    const { id } = req.params;
    const { day, note } = req.body;

    if (!day || !note) {
      return res.status(400).json({ 
        message: 'Day and note are required' 
      });
    }

    const itinerary = await Itinerary.findOne({
      _id: id,
      userId: req.user._id
    });

    if (!itinerary) {
      return res.status(404).json({ 
        message: 'Itinerary not found or access denied' 
      });
    }

    // Add the note
    itinerary.customizations.addedNotes.push({
      day: parseInt(day),
      note: note,
      addedAt: new Date()
    });

    await itinerary.save();

    res.json({
      success: true,
      message: 'Note added successfully',
      data: {
        note: {
          day: parseInt(day),
          note: note,
          addedAt: new Date()
        }
      }
    });
  } catch (error) {
    console.error('Add custom note error:', error);
    res.status(500).json({ 
      message: 'Failed to add note',
      error: error.message 
    });
  }
};

// @desc    Reset specific customization
// @route   DELETE /api/itineraries/:id/customizations/:modificationId
// @access  Private (requires JWT)
const resetCustomization = async (req, res) => {
  try {
    const { id, modificationId } = req.params;

    const itinerary = await Itinerary.findOne({
      _id: id,
      userId: req.user._id
    });

    if (!itinerary) {
      return res.status(404).json({ 
        message: 'Itinerary not found or access denied' 
      });
    }

    // Find the modification
    const modification = itinerary.customizations.modifiedActivities.id(modificationId);
    if (!modification) {
      return res.status(404).json({ 
        message: 'Modification not found' 
      });
    }

    // Find the day plan and reset the activity
    const dayPlan = itinerary.plan.dailyPlans.find(d => d.day === modification.day);
    if (dayPlan) {
      dayPlan[modification.timeSlot].activity = modification.originalActivity;
    }

    // Remove the modification
    itinerary.customizations.modifiedActivities.pull(modificationId);
    await itinerary.save();

    res.json({
      success: true,
      message: 'Customization reset successfully',
      data: {
        resetModification: modification
      }
    });
  } catch (error) {
    console.error('Reset customization error:', error);
    res.status(500).json({ 
      message: 'Failed to reset customization',
      error: error.message 
    });
  }
};

// @desc    Delete itinerary
// @route   DELETE /api/itineraries/:id
// @access  Private (requires JWT)
const deleteItinerary = async (req, res) => {
  try {
    const { id } = req.params;

    const itinerary = await Itinerary.findOneAndDelete({
      _id: id,
      userId: req.user._id
    });

    if (!itinerary) {
      return res.status(404).json({ 
        message: 'Itinerary not found or access denied' 
      });
    }

    res.json({
      success: true,
      message: 'Itinerary deleted successfully'
    });
  } catch (error) {
    console.error('Delete itinerary error:', error);
    res.status(500).json({ 
      message: 'Failed to delete itinerary',
      error: error.message 
    });
  }
};

export {
  generateItineraryForTrip,
  getUserItineraries,
  getItineraryById,
  getItineraryByTripId,
  generateAlternativeItineraryForTrip,
  updateItineraryStatus,
  provideItineraryFeedback,
  customizeItinerary,
  getCustomizedItinerary,
  addCustomNote,
  resetCustomization,
  deleteItinerary
};
